### ISSUE TITLE
Autoplace puts everything everywhere when font size is too big.

### ISSUE THREAD

**Issue by zuzuut** [Marr11317/saxophone-fingerings#3]
version 3 
when score is selected and plugin activated ,tenor one 
everything is scrambled  
fingering is waay up that puch score all way down  and they are in  vertical line not like on tutorial above score

**Comment by ecstrema** [comment]
hahahahaha, yes, that's because automatic placement gets in the way. 
Try right clicking one, then select-similar, and disable auto placement in the inspector

**Comment by ecstrema** [comment]
A screenshot would be welcome if I am wrong about the issue.

**Comment by ecstrema** [comment]
Other way to solve this is to increase the spacing

**Comment by zuzuut** [comment]
how to lower font size  by default it's 99.99
and that is main problem here
after i lower to 15 it's ok

**Comment by ecstrema** [comment]
open the generated files (those that end with .qml) in a text editor (any) At line 89, it says 
    text.fontSize = 100
Set that back to 15 or anything else you'd prefer.

I you want, I can add some preferences to this plugin if you believe it would be useful.

Are you sure you can read after printing if the size if 15?

**Comment by zuzuut** [comment]
well will test it but any bigger it fup all score lines  push them all down
is it possible to make bigger spacing between score lines to leave
them bigger ?

**Comment by ecstrema** [comment]
That's not what you should do to leave them bigger. You should add system breaks every few measures. Try selecting a measure and pressing enter.

**Comment by ecstrema** [comment]
I reduced the default font size.
It should now happen less often.
