### ISSUE TITLE
high f and high fis

### ISSUE THREAD

**Issue by hans3horns** [Marr11317/saxophone-fingerings#4]
Hi,
I applied this plugin for making a chart of fingerings for my pupil. The fingerings that are given for high f and high f-sharp are incorrect to my knowledge. The fingerings up to high e are all correct. The fingering that is given for high f is in fact the fingering for high f-sharp. The fingering that is given for high f-sharp is unknown to me but I guess that it is for so called top tones, possibly high g.
I don't know whether this is a bug in the plugin or in the Saxy font.
![Saxophone-fingerings](https://user-images.githubusercontent.com/68013543/152519174-f2912566-10ef-459d-89e7-aad8326b3b8a.png)
.

**Comment by ecstrema** [comment]
Thanks for the issue! 

You are right, this is a bug, and it belongs to the plugin. And you are also right for the higher register (the top G). I'll change that right now.

**Comment by ecstrema** [comment]
![image](https://user-images.githubusercontent.com/35939574/152629908-7c93b07f-05d6-49e9-8399-16796006cbbf.png)

There was the culprit: two 88 in a row:)

**Comment by ecstrema** [comment]
See https://github.com/Marr11317/saxophone-fingerings/commit/1419183a37747614aff01624eec4a4f41759d37e

The issue should be resolved now. You'll have to download the plugin.

Don't hesitate if you have any other issue!

**Comment by ecstrema** [comment]
Turns out I had made that error twice: https://github.com/Marr11317/saxophone-fingerings/commit/23a3a673b553da7ffc8553eb559ec38a9ff434b5

It should be fixed for real now.

**Comment by hans3horns** [comment]
Hi, I checked the updated plugin for soprano, alto, tenor and baritone sax. The fingerings up to high f-sharp are correct now. I never played or learned top tones so I couldn't check these, but I guess, looking at the code, that this will also be correct.
