### ISSUE TITLE
How to install? Notes seem wrong on my mac

### ISSUE THREAD

**Issue by vpicouet** [Marr11317/saxophone-fingerings#5]
Hello, 
thanks a lot for your amazing plugin.
I did not manage to install it properly, I only managed to run it from "create plugin"
![Capture d’écran, le 2023-11-30 à 20 01 29](https://github.com/ecstrema/saxophone-fingerings/assets/37241971/bda80189-fde1-4133-a5f9-ff83c7e2a57b)
I run the alto_sax_fingerings.qml but the notes seem wrong.
Do you know how I shoudl solve that?
Thanks a lot

**Comment by vpicouet** [comment]
I tried to reinstall it and am confronted to this issue:
![Capture d’écran, le 2023-11-30 à 21 53 45](https://github.com/ecstrema/saxophone-fingerings/assets/37241971/8b5d7776-422e-4dee-b1d7-92340e35d05d)
Thanks a lot for the help

**Comment by ecstrema** [comment]
Hey!

You're encountering the MuseScore 4 bug: You have downloaded the wrong version from the plugin page.

You'll have to head back to https://musescore.org/en/project/saxophone-fingerings, and download the MS3 version, since you're using MS3.

**Comment by ecstrema** [comment]
Here's a video showcasing the complete install process: https://www.youtube.com/watch?v=kXLm2XJ85nQ

**Comment by ecstrema** [comment]
It seems that this gives the concert pitch fingerings. You'll to go to the top right and toggle concert pitch off to see the right not, and thus the right fingering. 

If toggling on and off concert pitch does nothing, make sure you have selected the right instrument. (Press "i" to bring up the instruments dialog)

**Comment by vpicouet** [comment]
Thanks a lot! I installed it.
Unfortunately none of this change the notes... I'll try to ask around me, let me know if you think I did something wrong... thanks a lot!

https://github.com/ecstrema/saxophone-fingerings/assets/37241971/8350d03f-2440-454b-be98-2e58a4c0bef6

**Comment by ecstrema** [comment]
Hmm. There's definetely a problem in your score, since there is no transposition occuring when you toggle "concert pitch". The notes should change.

I would recommend adding an alto sax from the list in the instruments panel (press "i", search for sax, and double click on alto sax). 

Then, copy paste everything you had into the new alto sax part. You can then remove the old sax.

**Comment by ecstrema** [comment]
I'm closing this because I believe it's an error on your side and there's nothing I can do to fix it. 

Feel free to reopen it if you think I am mistaken.

**Comment by vpicouet** [comment]
Yup thanks a lot!!
